greetings = [
    "hello",
    "hi",
    "hey",
    "good morning",
    "good afternoon",
    "good evening",
    "howdy",
    "greetings",
    "welcome",
    "what's up",
    "what’s going on",
    "how are you",
    "how's it going",
    "how do you do",
    "nice to meet you",
    "pleased to meet you",
    "yo",
    "sup",
    "whassup",
    "wassup",
    "‘sup",
    "hey there",
    "heyyy",
    "hiya",
    "hiiii",
    "holla",
    "yo yo",
    "what’s good",
    "what's poppin",
    "what’s cookin",
    "howzit",
    "hey buddy",
    "how you doin’",
    "long time no see",
    "hola",
    "bonjour",
    "ciao",
    "namaste",
    "salam",
    "konnichiwa",
    "annyeong",
    "ola",
    "sawasdee",
    "hallo"
]

how_are_you_phrases = [
    "how are you",
    "how are you doing",
    "how’s it going",
    "how are things",
    "how have you been",
    "how do you do",
    "you good",
    "what’s up",
    "what up",
    "sup",
    "how you doing",
    "how r u",
    "how are u",
    "how u doing",
    "you okay",
    "are you okay",
    "everything good",
    "you doing fine",
    "what’s going on",
    "are you alright",
    "im fine how are you",
    "i'm fine how are you",
    "i am fine how are you",
    "i’m doing good how about you",
    "i’m okay how are you",
    "i’m great how are you",
    "all good how about you",
    "doing fine what about you"
]

who_are_you_phrases = [
    "who are you",
    "who r u",
    "what is your name",
    "what’s your name",
    "tell me your name",
    "identify yourself",
    "can you tell me your name",
    "who is this",
    "who am i talking to",
    "who am i speaking to",
    "what do i call you",
    "are you a bot",
    "are you human",
    "are you real",
    "you real",
    "are you alive",
    "what are you",
    "what even are you",
    "what kind of bot are you",
    "you ai",
    "are you ai"
]

bye_phrases = [
    "bye",
    "goodbye",
    "see you",
    "see ya",
    "later",
    "catch you later",
    "talk to you later",
    "see you later",
    "ciao",
    "peace",
    "farewell",
    "take care",
    "gotta go",
    "i'm out",
    "i have to go",
    "bye bye",
    "see ya later",
    "gtg",
    "ttyl",
    "adios",
    "ok bye",
    "ok goodnight",
    "good night",
    "night",
    "buh bye",
    "have a good day",
    "have a nice day",
    "until next time",
    "cya"
]

help_phrases = [
    "help",
    "i need help",
    "can you help me",
    "please help",
    "could you help me",
    "i want help",
    "how does this work",
    "how to use this",
    "what can you do",
    "what are your features",
    "show me what you can do",
    "what commands can i use",
    "tell me your functions",
    "help me out",
    "assist me",
    "give me help",
    "how does it work",
    "explain yourself",
    "what are you for",
    "what do i type",
    "i’m confused",
    "i dont understand",
    "i do not understand",
    "can you explain",
    "commands list",
    "usage",
    "instructions",
    "support",
    "show help",
    "how do i start",
    "how to begin",
    "how to start"
]

memory_phrases = [
    "what was the result",
    "last result",
    "previous result",
    "last answer",
    "previous answer",
    "what did i get",
    "tell me the last result"
]

questions = {
    "What is the capital of Japan?": "Tokyo",
    "Who discovered gravity when an apple fell on his head?": "Isaac Newton",
    "What is the smallest prime number?": "2",
    "Which language is primarily spoken in Brazil?": "Portuguese",
    "What does HTTP stand for?": "HyperText Transfer Protocol",
    "How many legs does a spider have?": "8",
    "What gas do plants absorb from the atmosphere?": "Carbon Dioxide",
    "What is the longest river in the world?": "Nile",
    "Who is the author of 'Harry Potter'?": "J.K. Rowling",
    "What planet do we live on?": "Earth",
    "What is the capital of France?": "Paris",
    "Who wrote the play 'Romeo and Juliet'?": "William Shakespeare",
    "What is the boiling point of water in Celsius?": "100",
    "Which planet is known as the Red Planet?": "Mars",
    "What is the largest mammal in the world?": "Blue Whale",
    "In which year did India gain independence?": "1947",
    "What is the chemical symbol for Gold?": "Au",
    "Who painted the Mona Lisa?": "Leonardo da Vinci",
    "What is the square root of 64?": "8",
    "Who is known as the father of computers?": "Charles Babbage"
}
